### ISSUE TITLE
Better compilation error reporting

### ISSUE THREAD

**Issue by JakubLinhart** [uoinfusion/Infusion#101]
- make sure that file name is clearly visible
- do not display full exception, just error message with line number and file name (test errors in initial script, other script, full script execution, partial script execution

Example of current compilation error message:
```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: c:\Users\jakub\sources\ultima\Infusion\scripts\UOErebor\Specs.csx(9,51): error CS1002: ; expected
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Infusion.Desktop.CSharpScriptEngine.<>c__DisplayClass11_1.<Execute>b__1() in c:\Users\jakub\sources\ultima\Infusion\src\Infusion.Desktop\CSharpScriptEngine.cs:line 103
```

**Comment by JakubLinhart** [comment]
Fixed by b7bbc2b556295f4786fe18f225c30109356977bd.
